#!/bin/bash

PROD_HOST="www@ex1"
PROD_PATH="/www/bots"
PROD_CONF=${PROD_PATH}"/../conf/bots.edn"

PROD_VAR="/www/bots/var"

JAR="tmp/target/bots.jar"

ssh $PROD_HOST mkdir -p ${PROD_VAR}/photos

# scp run stop ${PROD_HOST}:${PROD_PATH}

chmod g+r $JAR
scp $JAR ${PROD_HOST}:${PROD_PATH}
# scp conf/prod.edn ${PROD_HOST}:${PROD_CONF}

ssh $PROD_HOST $PROD_PATH/stop

#.
