#!/bin/bash

PROD_HOST="www@ex1"
PROD_PATH="/www/bots"
PROD_CONF=${PROD_PATH}"/../conf/bots.edn"

# PROD_VAR="/www/main/var"

JAR="tmp/target/bots.jar"

#ssh $PROD_HOST mkdir -p ${PROD_VAR}
scp run stop ${PROD_HOST}:${PROD_PATH}

chmod g+r $JAR
scp $JAR ${PROD_HOST}:${PROD_PATH}
# scp dev/prod.edn ${PROD_HOST}:${PROD_CONF}

ssh $PROD_HOST $PROD_PATH/stop

#.
