#!/bin/bash

# [Unit]
# Description=bots service
# Requires=network.target
#
# [Service]
# Type=simple
# User=www
# WorkingDirectory=/www/bots
# ExecStart=/www/bots/run
# Restart=always
# RestartSec=3
#
# [Install]
# WantedBy=multi-user.target

# systemctl reload-daemon
# systemctl enable www-bots
# systemctl start  www-bots

STDOUT="../log/skichat-out.log"
STDERR="../log/skichat-err.log"

exec java -jar skichat.jar ../conf/skichat.edn >> $STDOUT 2>>$STDERR &

PID=$!
echo $PID > .pid
wait $PID

#.
